import Menu from "@/components/parts/Menu";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeContext";
import Footer from "@/components/parts/Footer";

export const metadata = {
  title: "Meetings Summarizer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Menu/>
          {children}
          <div className="p-10"></div>
          <Footer/>
          </ThemeProvider>
      </body>
    </html>
  );
}