import Menu from "@/components/parts/Menu";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeContext";
import Footer from "@/components/parts/Footer";

export const metadata = {
  title: "Meetings Summarizer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen"> {/* Apply flex and min-height */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Menu />
          <div className="flex-grow"> {/* This ensures the content grows and pushes the footer down */}
            {children}
          </div>
          <Footer /> {/* The footer will be pushed to the bottom */}
        </ThemeProvider>
      </body>
    </html>
  );
}
